apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: mydaemon
  name: mydaemon
spec:
  selector:
    matchLabels:
      app: mydaemon
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydaemon
    spec:
      tolerations:
      - key: db-only
        operator: Exists
        effect: NoSchedule
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
